# Generated by Django 5.2.4 on 2025-08-04 10:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='Client IP address (IPv4 or IPv6)')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the request was made')),
                ('path', models.CharField(help_text='The requested URL path', max_length=500)),
            ],
            options={
                'verbose_name': 'Request Log',
                'verbose_name_plural': 'Request Logs',
                'db_table': 'ip_tracking_request_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['ip_address'], name='ip_tracking_ip_addr_589460_idx'), models.Index(fields=['timestamp'], name='ip_tracking_timesta_45e0c2_idx'), models.Index(fields=['path'], name='ip_tracking_path_220d7e_idx')],
            },
        ),
    ]
