# Generated by Django 5.2.4 on 2025-08-04 11:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address to block (IPv4 or IPv6)', unique=True)),
                ('reason', models.CharField(blank=True, help_text='Reason for blocking this IP address', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this IP was added to the blacklist')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this block is currently active')),
            ],
            options={
                'verbose_name': 'Blocked IP',
                'verbose_name_plural': 'Blocked IPs',
                'db_table': 'ip_tracking_blocked_ip',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ip_address'], name='ip_tracking_ip_addr_2b2c7d_idx'), models.Index(fields=['is_active'], name='ip_tracking_is_acti_f4fd15_idx')],
            },
        ),
    ]
